"""
utils/nse_universe.py  –  NSE stock universe for screening.

Contains NSE 500 stocks grouped by sector.
Screener pulls from this list each morning to find candidates.
"""

# NSE 500 — broad universe covering large, mid and small caps
NSE_UNIVERSE = [
    # Nifty 50 — Large caps
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY",
    "HINDUNILVR", "SBIN", "BHARTIARTL", "KOTAKBANK", "ITC",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",
    "BAJFINANCE", "WIPRO", "ULTRACEMCO", "ONGC", "NTPC",
    "POWERGRID", "SUNPHARMA", "TECHM", "HCLTECH", "NESTLEIND",
    "BAJAJFINSV", "TMPV", "ADANIENT", "JSWSTEEL", "TATASTEEL",
    "COALINDIA", "DIVISLAB", "DRREDDY", "CIPLA", "APOLLOHOSP",
    "EICHERMOT", "HEROMOTOCO", "BPCL", "GRASIM", "INDUSINDBK",
    "BRITANNIA", "TATACONSUM", "ADANIPORTS", "HINDALCO", "SBILIFE",
    "HDFCLIFE", "BAJAJ-AUTO", "M&M", "SHRIRAMFIN", "LTM",

    # Nifty Next 50 — Mid-large caps
    "VEDL", "SIEMENS", "HAVELLS", "PIDILITIND", "BERGEPAINT",
    "MARICO", "DABUR", "GODREJCP", "COLPAL", "MUTHOOTFIN",
    "CHOLAFIN", "PFC", "RECLTD", "IRFC", "NHPC",
    "TORNTPHARM", "LUPIN", "AUROPHARMA", "ALKEM", "BIOCON",
    "ZYDUSLIFE", "SYNGENE", "LAURUSLABS", "GLAND", "ABBOTINDIA",
    "PAGEIND", "WHIRLPOOL", "VOLTAS", "BLUESTARCO", "CROMPTON",
    "POLYCAB", "APLAPOLLO", "JINDALSAW", "RATNAMANI", "KALYANKJIL",
    "RAJESHEXPO", "TRENT", "NYKAA", "DMART", "ZOMATO",
    "NAUKRI", "PAYTM", "POLICYBZR", "IRCTC", "INDIGO",
    "SPICEJET", "GMRAIRPORT", "CONCOR", "ADANIGREEN", "TATAPOWER",

    # Nifty Midcap 150
    "AAPL", "AARTIDRUGS", "AARTIIND", "ABCAPITAL", "ABFRL",
    "ACC", "AEGISCHEM", "AFFLE", "AJANTPHARM", "AKZOINDIA",
    "APLLTD", "APTUS", "ASAHIINDIA", "ASTRAL", "ATUL",
    "AWHCL", "BAJAJHFL", "BALKRISIND", "BANDHANBNK", "BATAINDIA",
    "BAYERCROP", "BIKAJI", "BIRLAMONEY", "BSOFT", "CAMLINFINE",
    "CANFINHOME", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CESC",
    "CGPOWER", "CHENNPETRO", "CMSINFO", "COCHINSHIP", "COFORGE",
    "CRAFTSMAN", "CRISIL", "CSBBANK", "CYIENT", "DCMSHRIRAM",
    "DEEPAKNTR", "DELHIVERY", "DELTACORP", "DEVYANI", "DHANUKA",
    "DIXON", "EIDPARRY", "ELGIEQUIP", "EMAMILTD", "ENGINERSIN",
    "EPL", "ESABINDIA", "ESCORTS", "EXIDEIND", "FINEORG",
    "FINPIPE", "FLUOROCHEM", "FMGOETZE", "GAIL", "GALAXY",
    "GESHIP", "GILLETTE", "GLAXO", "GNFC", "GODREJIND",
    "GPIL", "GRINDWELL", "GSFC", "GSPL", "HAPPSTMNDS",
    "HATSUN", "HEXT", "HIKAL", "HINDCOPPER", "HINDPETRO",
    "HONASA", "HSCL", "HUDCO", "IDFCFIRSTB", "IEX",
    "IFBIND", "IIFL", "INDIANB", "INDIAMART", "INDHOTEL",
    "INTELLECT", "IOB", "IPCALAB", "JBCHEPHARM", "JKTYRE",
    "JLHL", "JMFINANCIL", "JUBLFOOD", "JUBLINGREA", "JUSTDIAL",
    "KANSAINER", "KARURVYSYA", "KAYNES", "KFINTECH", "KPITTECH",
    "KRBL", "LALPATHLAB", "LATENTVIEW", "LEMONTREE", "LICHSGFIN",
    "LICI", "LINDEINDIA", "LXCHEM", "MAHABANK", "MANAPPURAM",
    "MANKIND", "MASTEK", "MAXHEALTH", "METROPOLIS", "MFSL",
    "MGL", "MINDACORP", "MMTC", "MOIL",
    "MOTHERSON", "MPHASIS", "MSTCLTD", "NATCOPHARM", "NAVINFLUOR",
    "NESCO", "NIITLTD", "NLCINDIA", "NMDC", "NOCIL",

    # Newly listed / high interest stocks
    "VAML", "ZSWSTL", "WAAREEENER", "RVNL", "RAILTEL",
    "IREDA", "SJVN", "MAZDOCK", "GRSE", "BEL",
    "HAL", "BEML", "BHEL", "NBCC", "RITES",
    "TIINDIA", "SOLARINDS", "IDEAFORGE", "RATEGAIN", "ZAGGLE",
]

# Sectors mapped for sector-rotation logic (future use)
SECTOR_MAP = {
    "IT":          ["TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "LTM",
                    "MPHASIS", "COFORGE", "KPITTECH", "HAPPSTMNDS"],
    "BANKING":     ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK",
                    "INDUSINDBK", "BANDHANBNK", "IDFCFIRSTB", "KARURVYSYA"],
    "PHARMA":      ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "LUPIN",
                    "AUROPHARMA", "ALKEM", "BIOCON", "IPCALAB"],
    "AUTO":        ["MARUTI", "TMPV", "M&M", "BAJAJ-AUTO", "HEROMOTOCO",
                    "EICHERMOT", "ESCORTS", "MOTHERSON"],
    "FMCG":        ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "MARICO",
                    "DABUR", "GODREJCP", "COLPAL", "EMAMILTD"],
    "METALS":      ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL", "NMDC",
                    "MOIL", "HINDCOPPER", "VAML"],
    "ENERGY":      ["RELIANCE", "ONGC", "BPCL", "HINDPETRO", "GAIL",
                    "TATAPOWER", "ADANIGREEN", "ADANIPORTS"],
    "INFRA":       ["LT", "NTPC", "POWERGRID", "COALINDIA", "BEL",
                    "HAL", "BHEL", "RVNL", "IRFC"],
}
